close all; clear all; clf;

time=0:20:20*4095;
fid=fopen("open.dat");
val=fread(fid,4096,"uint16")';
val=-2*(val-956)/(2974-956)+1;

plot(time,val,"linewidth",2);
hold on;
ylim([-1.2 1.2]);
xlim([time(1) time(end)]);
start_value=mean(val(1:100));
end_value=mean(val(240:4096));
rise20_value=start_value+0.2*(end_value-start_value);
rise80_value=start_value+0.8*(end_value-start_value);
rise20_position=find(val>=rise20_value)(1);
rise20_value=val(rise20_position);
rise80_position=find(val>=rise80_value)(1);
rise80_value=val(rise80_position);
yticks([-1:0.2:1]);
grid off;
grid minor on;
l=xlabel("Cas (ps)");
ylabel("Koeficient odrazu (-)");
hold on;
saveas(gca, '/home/msboss/Documents/diplomova_prace/LaTeX/images/self-measurements/measured_open.eps','epsc');
plot([time(1) time(end)], rise20_value.*ones(1,2),"color","r");
plot([time(1) time(end)], rise80_value.*ones(1,2),"color","r");
plot(time(rise20_position).*ones(1,2), [-10 10],"color","r");
plot(time(rise80_position).*ones(1,2), [-10 10],"color","r");
xlim([2000 3000]);
saveas(gca, '/home/msboss/Documents/diplomova_prace/LaTeX/images/self-measurements/measure_open_risetime.eps','epsc');

figure();
fid=fopen("short.dat");
val=fread(fid,4096,"uint16")';
val=-2*(val-904)/(2913-904)+1;

plot(time,val,"linewidth",2);
hold on;
ylim([-1.2 1.2]);
xlim([time(1) time(end)]);
start_value=mean(val(1:100));
end_value=mean(val(240:4096));
rise20_value=start_value+0.2*(end_value-start_value);
rise80_value=start_value+0.8*(end_value-start_value);
rise20_position=find(val<=rise20_value)(1);
rise20_value=val(rise20_position);
rise80_position=find(val<=rise80_value)(1);
rise80_value=val(rise80_position);
yticks([-1:0.2:1]);
grid off;
grid minor on;
l=xlabel("Cas (ps)");
ylabel("Koeficient odrazu (-)");
hold on;
saveas(gca, '/home/msboss/Documents/diplomova_prace/LaTeX/images/self-measurements/measured_short.eps','epsc');
plot([time(1) time(end)], rise20_value.*ones(1,2),"color","r");
plot([time(1) time(end)], rise80_value.*ones(1,2),"color","r");
plot(time(rise20_position).*ones(1,2), [-10 10],"color","r");
plot(time(rise80_position).*ones(1,2), [-10 10],"color","r");
xlim([2000 3500]);
saveas(gca, '/home/msboss/Documents/diplomova_prace/LaTeX/images/self-measurements/measure_short_risetime.eps','epsc');

figure();
fid=fopen("load.dat");
val=fread(fid,4096,"uint16")';
val=-2*(val-972)/(2996-972)+1;

plot(time,val,"linewidth",2);
hold on;
ylim([-1.2 1.2]);
xlim([time(1) time(end)]);
yticks([-1:0.2:1]);
grid off;
grid minor on;
l=xlabel("Cas (ps)");
ylabel("Koeficient odrazu (-)");
hold on;
saveas(gca, '/home/msboss/Documents/diplomova_prace/LaTeX/images/self-measurements/measured_load.eps','epsc');
