close all;
load calibration_thesis.cal;
load measurement2.dat;
data_length=length(semicalibrated_data);

figure();
plot(0:4095,calibration_data.open);
hold on;
plot(0:4095,calibration_data.short);
plot(0:4095,calibration_data.load);
xlim([0 4095]);
grid off;
grid minor on;
xlabel('Cas (ps)');
ylabel('Koeficient odrazu (-)');
ylim([-1.6 1.6]);
saveas(gca, '/home/msboss/Documents/diplomova_prace/LaTeX/images/gui/standards_after_autocalibration.eps','epsc');

calibration_data.open=calibration_data.open-calibration_data.load;
calibration_data.short=calibration_data.short-calibration_data.load;
semicalibrated_data=semicalibrated_data-calibration_data.load;
%semicalibrated_data=[calibration_data.open(1).*ones(1,100) calibration_data.open(1:end-100)];
%semicalibrated_data=[semicalibrated_data(1).*ones(1,100) semicalibrated_data(1:end-100)];

calibration_data.load=calibration_data.load-calibration_data.load;

figure();
plot(0:4095,calibration_data.open);
hold on;
plot(0:4095,calibration_data.short);
plot(0:4095,calibration_data.load);
xlim([0 4095]);
grid off;
grid minor on;
xlabel('Cas (ps)');
ylabel('Koeficient odrazu (-)');
ylim([-1 1]);
saveas(gca, '/home/msboss/Documents/diplomova_prace/LaTeX/images/gui/standards_after_load_calibration.eps','epsc');

S11L=fft(calibration_data.load);
S11O=fft(calibration_data.open);
S11S=fft(calibration_data.short);
S11M=fft(semicalibrated_data);
%S11M=fft(calibration_data.load);

figure();
subplot(3,1,1);
plot(calibration_data.open);
title('Open response');
xlim([1 data_length]);
ylim([-2 2]);
grid off;
grid minor on;
subplot(3,1,2);
plot(calibration_data.short);
title('Short response');
xlim([1 data_length]);
ylim([-2 2]);
grid off;
grid minor on;
subplot(3,1,3);
plot(calibration_data.load);
title('Load response');
xlim([1 data_length]);
ylim([-2 2]);
grid off;
grid minor on;

figure();
subplot(3,1,1);
plot(20*log(abs(S11O)/4096));
title('Open spectrum');
xlim([1 data_length]);
grid off;
grid minor on;
subplot(3,1,2);
plot(20*log(abs(S11S)/4096));
title('Short spectrum');
xlim([1 data_length]);
grid off;
grid minor on;
subplot(3,1,3);
plot(20*log(abs(S11L)/4096));
title('Load spectrum');
xlim([1 data_length]);
grid off;
grid minor on;

%Ed=S11L;
%Er=2.*( ( (S11O-S11L).*S11S - S11L.*S11O + S11L.*S11L) ./ (S11S-S11O) );
%Es=-( (S11S+S11O-2.*S11L) ./ (S11S-S11O) );

Ed=0;
Er=2.*( ( S11O.*S11S ) ./ (S11S-S11O) );
Es=-( (S11S+S11O) ./ (S11S-S11O) );

figure();
subplot(3,1,1);
plot(20*log(abs(Ed)/4096));
title('Directivity error spectrum');
xlim([1 data_length]);
grid off;
grid minor on;
subplot(3,1,2);
plot(20*log(abs(Er)/4096));
title('Source match error spectrum');
xlim([1 data_length]);
grid off;
grid minor on;
subplot(3,1,3);
plot(20*log(abs(Es)/4096));
title('Tracking error spectrum');
xlim([1 data_length]);
grid off;
grid minor on;

%S11M_corr= (S11M-Ed) ./ ( Es.*(S11M-Ed)+Er );
S11M_corr= S11M ./ ( Es.*S11M+Er );

figure();
subplot(2,2,1);
plot(20*log(abs(S11M)));
title('Semicalibrated measurement spectrum');
xlim([1 data_length]);
grid off;
grid minor on;
subplot(2,2,2);
plot(real(ifft(S11M)));
title('Semicalibrated measurement response');
xlim([1 data_length]);
ylim([-2 2]);
grid off;
grid minor on;
subplot(2,2,3);
plot(20*log(abs(S11M_corr)));
title('Fully calibrated measurement spectrum');
xlim([1 data_length]);
grid off;
grid minor on;
subplot(2,2,4);
corrected_data=ifft(S11M_corr);
plot(real(corrected_data));
title('Fully calibrated measurement response');
xlim([1 data_length]);
ylim([-2 2]);
grid off;
grid minor on;