This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./diplomova_prace.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file diplomova_prace.acn....done (96 entries accepted, 0 rejected).
Sorting entries....done (697 comparisons).
Generating output file diplomova_prace.acr....done (109 lines written, 0 warnings).
Output written in diplomova_prace.acr.
Transcript written in diplomova_prace.alg.
