This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./diplomovy_projekt.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file diplomovy_projekt.acn....done (61 entries accepted, 0 rejected).
Sorting entries....done (353 comparisons).
Generating output file diplomovy_projekt.acr....done (73 lines written, 0 warnings).
Output written in diplomovy_projekt.acr.
Transcript written in diplomovy_projekt.alg.
